name: kgiton_sdk_example
description: Example app untuk KGiTON SDK
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  
  # KGiTON SDK
  kgiton_sdk:
    path: ../
    # OR from GitHub:
    # git:
    #   url: https://github.com/kuldii/flutter-kgiton-sdk.git
    #   path: flutter/kgiton_sdk
  
  # Permissions
  permission_handler: ^11.4.0
  
  # Utilities
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
